services:
  - type: web
    name: shein-voucher-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: PORT
        value: 8080
      - key: MAX_WORKERS
        value: "20"
      - key: REQUEST_TIMEOUT
        value: "12"
    plan: free
    autoDeploy: true
    healthCheckPath: /health